# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o-0VGNbL-XrtJyz8vgR1RflKX5h8967a
"""

# Upload the datasets to Colab
from google.colab import files
uploaded = files.upload()

# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
import zipfile
import os
import cv2

sensor_path = "/content/dungeon_sensorstats_partC.csv"
zip_path = "/content/dungeon_images_colour80.zip"
extracted_dir = "/content/sample_data/images_folder"

# Step 3: Extract the zip file (images)
if not os.path.exists(extracted_dir):
    os.makedirs(extracted_dir)  # Create folder if it doesn’t exist
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extracted_dir)
image_dir = extracted_dir  # Path to extracted images

# Check if sensor file exists, upload if missing
if not os.path.exists(sensor_path):
    print(f"File not found at {sensor_path}. Please upload dungeon_sensorstats.partC.csv")
    uploaded = files.upload()
    for filename in uploaded.keys():
        if "dungeon_sensorstats.partC.csv" in filename:
            os.rename(filename, sensor_path)
            print(f"Moved {filename} to {sensor_path}")
        else:
            print("Uploaded file doesn’t match expected name.")
            raise FileNotFoundError("Incorrect file uploaded")

# Step 2: Load the sensor data
sensor_data = pd.read_csv(sensor_path)
print("Sensor data shape:", sensor_data.shape)
print(sensor_data.head())

# Step 3: Handle missing values in sensor data
# Check for missing values
print("Missing values in sensor data:")
print(sensor_data.isnull().sum())

# Impute missing 'race' value with the most common race
most_common_race = sensor_data['race'].mode()[0]
sensor_data['race'].fillna(most_common_race, inplace=True)
print(f"Imputed 1 missing 'race' value with: {most_common_race}")

# Impute missing numeric values with the mean of each column
numeric_columns = ['stench', 'sound', 'heat', 'intelligence', 'height', 'weight', 'strength', 'bribe']
for col in numeric_columns:
    sensor_data[col].fillna(sensor_data[col].mean(), inplace=True)

# Verify no missing values remain
print("Missing values after imputation:")
print(sensor_data.isnull().sum())

# Step 4: Prepare sensor data (X) and target (Y)
# Extract numeric features for X
sensor_X = sensor_data[numeric_columns]

# Normalize the sensor data
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
sensor_X = scaler.fit_transform(sensor_X)
sensor_X = pd.DataFrame(sensor_X, columns=numeric_columns)
print("Normalized sensor_X shape:", sensor_X.shape)
print(sensor_X.head())

# Extract the target variable (flight) - not needed for Task 2 but included for completeness
flight_Y = sensor_data['flight'].values
print("flight_Y shape:", flight_Y.shape)
print("flight_Y distribution:", np.bincount(flight_Y))

# Task 2: Unsupervised Learning - K-Means Clustering on Sensor Data
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Step 1: Determine the optimal number of clusters using the elbow method
inertia = []
silhouette_scores = []
k_range = range(2, 11)  # Test k from 2 to 10
for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(sensor_X)
    inertia.append(kmeans.inertia_)
    if k > 1:  # Silhouette score requires at least 2 clusters
        score = silhouette_score(sensor_X, kmeans.labels_)
        silhouette_scores.append(score)
    else:
        silhouette_scores.append(0)

# Plot the elbow curve
plt.figure(figsize=(6, 4))
plt.plot(k_range, inertia, marker='o')
plt.title("Elbow Method for Optimal k")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Inertia")
plt.savefig("elbow_curve.png", dpi=300, bbox_inches="tight")
plt.show()

# Plot the silhouette scores
plt.figure(figsize=(6, 4))
plt.plot(k_range, silhouette_scores, marker='o')
plt.title("Silhouette Scores for Different k")
plt.xlabel("Number of Clusters (k)")
plt.ylabel("Silhouette Score")
plt.savefig("silhouette_scores.png", dpi=300, bbox_inches="tight")
plt.show()

# Step 2: Apply K-Means with the chosen k (e.g., k=5, based on elbow and silhouette analysis)
optimal_k = 5  # Adjust based on elbow and silhouette plots
kmeans = KMeans(n_clusters=optimal_k, random_state=42)
cluster_labels = kmeans.fit_predict(sensor_X)

# Step 3: Evaluate clustering
silhouette_avg = silhouette_score(sensor_X, cluster_labels)
print(f"Silhouette Score for k={optimal_k}: {silhouette_avg:.4f}")
print(f"Inertia for k={optimal_k}: {kmeans.inertia_:.4f}")

# Step 4: Visualize clusters using PCA
pca = PCA(n_components=2)
sensor_pca = pca.fit_transform(sensor_X)
explained_variance = pca.explained_variance_ratio_.sum()
print(f"Explained variance ratio by 2 PCA components: {explained_variance:.4f}")

plt.figure(figsize=(8, 6))
sns.scatterplot(x=sensor_pca[:, 0], y=sensor_pca[:, 1], hue=cluster_labels, palette="tab10")
plt.title(f"K-Means Clusters (k={optimal_k}, PCA Projection)")
plt.xlabel("PCA Component 1")
plt.ylabel("PCA Component 2")
plt.savefig("cluster_visualization.png", dpi=300, bbox_inches="tight")
plt.show()

# Step 5: Compare clusters to race for analysis
cluster_race_crosstab = pd.crosstab(sensor_data["race"], cluster_labels)
print("Crosstab of race vs cluster:")
print(cluster_race_crosstab)

# Save the crosstab as a table for the report (optional, can be formatted in LaTeX)
cluster_race_crosstab.to_csv("cluster_race_crosstab.csv")

# Task 3: Reinforcement Learning - DQN for Maze Navigation with Enemies

# Commented out IPython magic to ensure Python compatibility.
# Task 3: Reinforcement Learning - DQN for Maze Navigation with Enemies
# Step 1: Install dependencies and clone the repository
!pip install gym
!git clone https://github.com/uobcll/SEMTM0016_DungeonMazeWorld
# %cd SEMTM0016_DungeonMazeWorld

# Step 2: Import libraries
import gym
import numpy as np
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from collections import deque
import random
from core.dungeonworld_grid import MazeGrid
from envs.simple_dungeonworld_env import DungeonMazeEnv, Actions, Directions

# Check the contents of the repository
!ls

# Explore the envs directory
!ls envs

# View the contents of simple_dungeonworld_env.py to find the class name
!cat envs/simple_dungeonworld_env.py

from envs.simple_dungeonworld_env import DungeonMazeEnv

# Fix the grid_size error in simple_dungeonworld_env.py
# Read the file
file_path = "/content/SEMTM0016_DungeonMazeWorld/envs/simple_dungeonworld_env.py"
with open(file_path, "r") as file:
    lines = file.readlines()

# Find the __init__ method and reorder the lines
for i, line in enumerate(lines):
    if "def __init__(self, render_mode=None, grid_size=16):" in line:
        init_start = i
        break

# Find the lines within __init__ and reorder them
for j in range(init_start, len(lines)):
    if lines[j].strip().startswith("self.grid_size = grid_size"):
        grid_size_line = lines[j]
    elif lines[j].strip().startswith("self.window_size = 512"):
        window_size_line = lines[j]
    elif lines[j].strip().startswith("self.action_space = spaces.Discrete(len(Actions))"):
        action_space_line = lines[j]
    elif lines[j].strip().startswith("self.observation_space = spaces.Dict("):
        obs_space_start = j
        break

# Reorder: Ensure self.grid_size is assigned before it's used
lines[init_start + 1:init_start + 4] = [grid_size_line, window_size_line, action_space_line]

# Write the modified file back
with open(file_path, "w") as file:
    file.writelines(lines)

print("Updated simple_dungeonworld_env.py to fix the grid_size error.")

# View the updated file to confirm the change
!cat /content/SEMTM0016_DungeonMazeWorld/envs/simple_dungeonworld_env.py

def __init__(self, render_mode=None, grid_size=16):
    self.grid_size = grid_size
    self.window_size = 512
    self.action_space = spaces.Discrete(len(Actions))
    self.observation_space = spaces.Dict(
        {
            "robot_position": spaces.Box(0, grid_size - 1, shape=(2,), dtype=int),
            "robot_direction": spaces.Discrete(len(Directions)),
            "robot_camera_view": spaces.Box(low=0, high=255, shape=(20, 20), dtype=np.int32),
            "target_position": spaces.Box(0, grid_size - 1, shape=(2,), dtype=int),
        }
    )

# Update the observation_space to use self.grid_size
# Read the file again
with open(file_path, "r") as file:
    lines = file.readlines()

# Replace grid_size with self.grid_size in the observation_space definition
for i, line in enumerate(lines):
    if "spaces.Box(0, grid_size - 1" in line:
        lines[i] = line.replace("grid_size - 1", "self.grid_size - 1")

# Write the modified file back
with open(file_path, "w") as file:
    file.writelines(lines)

print("Updated simple_dungeonworld_env.py to use self.grid_size in observation_space.")

# View the updated file to confirm the change
!cat /content/SEMTM0016_DungeonMazeWorld/envs/simple_dungeonworld_env.py

# Remove redundant lines in simple_dungeonworld_env.py
# Read the file
file_path = "/content/SEMTM0016_DungeonMazeWorld/envs/simple_dungeonworld_env.py"
with open(file_path, "r") as file:
    lines = file.readlines()

# Find the __init__ method and remove duplicate lines
init_start = None
for i, line in enumerate(lines):
    if "def __init__(self, render_mode=None, grid_size=16):" in line:
        init_start = i
        break

# Remove the duplicate lines
lines_to_keep = []
in_init = False
for i, line in enumerate(lines):
    if i == init_start:
        in_init = True
        lines_to_keep.append(line)
    elif in_init and line.strip() == 'self.grid_size = grid_size' and lines[i-1].strip() == 'self.grid_size = grid_size':
        continue  # Skip the duplicate self.grid_size
    elif in_init and line.strip() == 'self.window_size = 512' and lines[i-1].strip() == 'self.window_size = 512':
        continue  # Skip the duplicate self.window_size
    elif in_init and line.strip() == 'self.action_space = spaces.Discrete(len(Actions))' and lines[i-2].strip() == 'self.action_space = spaces.Discrete(len(Actions))':
        continue  # Skip the duplicate self.action_space
    elif in_init and line.strip() == 'self.observation_space = spaces.Dict(':
        in_init = False
        lines_to_keep.append(line)
    else:
        lines_to_keep.append(line)

# Write the modified file back
with open(file_path, "w") as file:
    file.writelines(lines_to_keep)

print("Removed redundant lines in simple_dungeonworld_env.py.")

# View the updated file to confirm the change
!cat /content/SEMTM0016_DungeonMazeWorld/envs/simple_dungeonworld_env.py

# Test the environment initialization
from envs.simple_dungeonworld_env import DungeonMazeEnv

# Initialize the environment
env = DungeonMazeEnv(grid_size=6, render_mode=None)
print("Environment initialized successfully!")

# Step 3: Modify the DungeonMazeEnv to adjust rewards and allow an empty maze
class AdjustedDungeonMazeEnv(DungeonMazeEnv):
    def __init__(self, render_mode=None, grid_size=6, empty_maze=False):
        super().__init__(render_mode=render_mode, grid_size=grid_size)
        self.empty_maze = empty_maze

    def step(self, action):
        # Get the position in front of the agent (similar to DungeonMazeEnv.step)
        position_in_front = self.robot_position.copy()
        if self.robot_direction == Directions.north:
            position_in_front[1] -= 1
        elif self.robot_direction == Directions.east:
            position_in_front[0] += 1
        elif self.robot_direction == Directions.south:
            position_in_front[1] += 1
        elif self.robot_direction == Directions.west:
            position_in_front[0] -= 1

        # Check if the position in front is within bounds
        x, y = position_in_front
        if x < 0 or x >= self.grid_size or y < 0 or y >= self.grid_size:
            # Out of bounds, treat as a wall collision
            reward = -20  # Wall penalty (as defined in AdjustedDungeonMazeEnv)
            done = True
            truncated = False
            info = {}
            next_state = self.get_observations()  # Current state (agent doesn't move)
            return next_state, reward, done, truncated, info

        # If in bounds, proceed with the parent step method
        next_state, reward, done, truncated, info = super().step(action)

        # Adjust the step penalty
        if reward == -1:  # Original step penalty
            reward = -0.1  # New step penalty
        elif reward == -100:  # Original wall penalty
            reward = -20  # New wall penalty

        # Add a distance-based reward
        agent_pos = next_state["robot_position"]
        target_pos = next_state["target_position"]
        distance = np.linalg.norm(agent_pos - target_pos)
        max_distance = np.sqrt(2 * (self.grid_size - 1)**2)  # Max distance in grid (diagonal)
        distance_reward = (max_distance - distance) / max_distance  # Normalized distance reward (0 to 1)
        reward += distance_reward  # Small positive reward for getting closer to the target

        return next_state, reward, done, truncated, info

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        # Create the grid capturing the maze as walls
        self.maze = MazeGrid(size=self.grid_size, empty=self.empty_maze, np_rng=self.np_random)
        # Set the target location
        self.target_position = np.array([self.grid_size - 2, self.grid_size - 2])
        # Set the robot's location, direction, initial camera view
        self.robot_position = np.array([1, 1])
        self.robot_direction = Directions.south
        self.robot_camera_view = self.get_robot_camera_view()
        # Update the observations
        observation = self.get_observations()
        if self.render_mode == "human":
            self._render_frame()
        return observation, {}

    def get_robot_camera_view(self):
        # Get the position in front of the agent
        position_in_front = self.robot_position.copy()
        if self.robot_direction == Directions.north:
            position_in_front[1] -= 1
        elif self.robot_direction == Directions.east:
            position_in_front[0] += 1
        elif self.robot_direction == Directions.south:
            position_in_front[1] += 1
        elif self.robot_direction == Directions.west:
            position_in_front[0] -= 1

        # Check if the position is within bounds
        x, y = position_in_front
        if x < 0 or x >= self.grid_size or y < 0 or y >= self.grid_size:
            # Out of bounds, so assume it's a wall
            return np.ones((20, 20), dtype=np.int32) * 255

        # Get the contents of the cell in front of the agent
        cell_in_front = self.maze.get_cell_item(*position_in_front)

        if cell_in_front is None:
            # Shouldn't happen due to the bounds check, but keep for safety
            return np.ones((20, 20), dtype=np.int32) * 255
        elif cell_in_front == 1:
            # Wall
            return np.ones((20, 20), dtype=np.int32) * 255
        else:
            # Empty space
            return np.zeros((20, 20), dtype=np.int32)  # Fixed the syntax error

# Step 4: Initialize the environment with adjusted rewards, 6x6 grid, and empty maze
env = AdjustedDungeonMazeEnv(grid_size=6, render_mode=None, empty_maze=True)  # 6x6 grid, empty maze
enemy_positions = [(3, 4)]  # Single enemy
env = DungeonMazeWithEnemies(env, enemy_positions)

# Step 5: Preprocess observation with normalization
def preprocess_observation(observation):
    robot_pos = observation["robot_position"] / 6.0  # Normalize by grid_size (6)
    robot_dir = np.array([observation["robot_direction"]]) / 3.0  # Normalize by max direction (3)
    target_pos = observation["target_position"] / 6.0  # Normalize by grid_size (6)
    state = np.concatenate([robot_pos, robot_dir, target_pos])
    return state

# Test the preprocessing function
observation = env.reset()[0]  # Get the initial observation
state = preprocess_observation(observation)
print("Preprocessed state:", state)
print("State shape:", state.shape)

# Step 6: Define the DQN Agent with adjusted hyperparameters and exploration warm-up
class DQNAgent:
    def __init__(self, state_size, action_size):
        self.state_size = state_size
        self.action_size = action_size
        self.memory = deque(maxlen=2000)
        self.gamma = 0.95
        self.epsilon = 1.0  # Start with high epsilon for exploration
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.learning_rate = 0.0005
        self.model = self._build_model()
        self.steps = 0  # Track total steps for warm-up
        self.warmup_steps = 100  # Number of steps to fill replay buffer before training

    def _build_model(self):
        model = models.Sequential()
        model.add(layers.Dense(64, input_dim=self.state_size, activation='relu'))  # Increased to 64 units
        model.add(layers.Dense(64, activation='relu'))  # Increased to 64 units
        model.add(layers.Dense(self.action_size, activation='linear'))
        model.compile(loss='mse', optimizer=tf.keras.optimizers.Adam(learning_rate=self.learning_rate))
        return model

    def remember(self, state, action, reward, next_state, done):
        self.memory.append((state, action, reward, next_state, done))

    def act(self, state):
        self.steps += 1
        if self.steps < self.warmup_steps or np.random.rand() <= self.epsilon:
            return random.randrange(self.action_size)
        act_values = self.model.predict(state, verbose=0)
        return np.argmax(act_values[0])

    def replay(self, batch_size):
        if self.steps < self.warmup_steps:
            return  # Skip training during warm-up
        minibatch = random.sample(self.memory, batch_size)
        states = np.array([experience[0][0] for experience in minibatch])
        next_states = np.array([experience[3][0] for experience in minibatch])
        actions = np.array([experience[1] for experience in minibatch])
        rewards = np.array([experience[2] for experience in minibatch])
        dones = np.array([experience[4] for experience in minibatch])
        targets = self.model.predict(states, verbose=0)
        next_q_values = self.model.predict(next_states, verbose=0)
        for i in range(batch_size):
            if not dones[i]:
                targets[i][actions[i]] = rewards[i] + self.gamma * np.amax(next_q_values[i])
            else:
                targets[i][actions[i]] = rewards[i]
        self.model.fit(states, targets, epochs=1, verbose=0)
        if self.epsilon > self.epsilon_min:
            self.epsilon *= self.epsilon_decay

# Step 7: Train the DQN Agent (Second Run)
state_size = 5
action_size = env.action_space.n
agent = DQNAgent(state_size, action_size)
episodes = 500
batch_size = 32
rewards = []  # Reset the rewards list for the new training run
replay_frequency = 4

for e in range(episodes):
    observation = env.reset()[0]
    state = preprocess_observation(observation)
    state = np.reshape(state, [1, state_size])
    total_reward = 0
    for time in range(50):
        action = agent.act(state)
        next_observation, reward, done, truncated, _ = env.step(action)
        total_reward += reward
        next_state = preprocess_observation(next_observation)
        next_state = np.reshape(next_state, [1, state_size])
        agent.remember(state, action, reward, next_state, done)
        state = next_state
        if done or truncated:
            print(f"Episode {e+1}/{episodes}, Reward: {total_reward:.2f}, Epsilon: {agent.epsilon:.2f}")
            break
        if len(agent.memory) > batch_size and time % replay_frequency == 0:
            agent.replay(batch_size)
    rewards.append(total_reward)

# Plot the rewards from the second training run (374 episodes)
plt.figure(figsize=(8, 6))
plt.plot(rewards)
plt.title("DQN Training Rewards Over Episodes")
plt.xlabel("Episode")
plt.ylabel("Total Reward")
plt.savefig("dqn_rewards_second_run.png", dpi=300, bbox_inches="tight")
plt.show()

# Evaluate the trained agent from the second run
eval_episodes = 10
eval_rewards = []
for e in range(eval_episodes):
    observation = env.reset()[0]
    state = preprocess_observation(observation)
    state = np.reshape(state, [1, state_size])
    total_reward = 0
    for time in range(50):
        action = agent.act(state)
        next_observation, reward, done, truncated, _ = env.step(action)
        total_reward += reward
        next_state = preprocess_observation(next_observation)
        next_state = np.reshape(next_state, [1, state_size])
        state = next_state
        if done or truncated:
            break
    eval_rewards.append(total_reward)
avg_eval_reward = np.mean(eval_rewards)
print(f"Average evaluation reward over {eval_episodes} episodes: {avg_eval_reward:.2f}")