# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1reqG248PBhAVz8j95eIMxE6f5HwL2TR-
"""

# Commented out IPython magic to ensure Python compatibility.
# Step 1: Install dependencies and clone the repository
!pip install gym
!git clone https://github.com/uobcll/SEMTM0016_DungeonMazeWorld
# %cd SEMTM0016_DungeonMazeWorld

# Step 2: Import libraries
import gym
import numpy as np
import tensorflow as tf
from tensorflow.keras import models, layers
import matplotlib.pyplot as plt
from collections import deque
import random
from core.dungeonworld_grid import MazeGrid
from envs.simple_dungeonworld_env import DungeonMazeEnv, Actions, Directions

import sys
sys.path.append('/content/SEMNTM016_DungeonMazeWorld')

# Initialize the environment
env = DungeonMazeEnv(grid_size=6)

# Reset the environment and get the initial observation
observation = env.reset()
print("Initial observation:", observation)
print("Robot position:", env.robot_position)
print("Robot direction:", env.robot_direction)

# Take a sample step (move forwards, action=2)
next_observation, reward, terminated, _, _ = env.step(2)
print("Next observation:", next_observation)
print("Reward:", reward)
print("Terminated:", terminated)

# Define the rollout function
def rollout(env, policy, max_steps=100):
    trajectory = []
    observation = env.reset()
    # State is a tuple of (position, direction)
    state = (env.robot_position.copy(), env.robot_direction)  # .copy() to avoid reference issues
    for _ in range(max_steps):
        action = policy(state)  # Get action from policy
        next_observation, reward, terminated, _, _ = env.step(action)
        trajectory.append((state, action, reward))
        # Update state
        state = (env.robot_position.copy(), env.robot_direction)
        if terminated:
            break
    return trajectory

# Test with a dummy policy (always move forward)
def dummy_policy(state):
    return 2  # Action 2 = move forwards

# Initialize environment
env = DungeonMazeEnv(grid_size=6)

# Run rollout
trajectory = rollout(env, dummy_policy)
print("Trajectory length:", len(trajectory))
print("First few steps:", trajectory[:3])  # Print first 3 steps

# Rollout function
def rollout(env, policy, max_steps=100):
    trajectory = []
    observation = env.reset()
    state = (env.robot_position.copy(), env.robot_direction)
    for _ in range(max_steps):
        action = policy(state)
        next_observation, reward, terminated, _, _ = env.step(action)
        trajectory.append((state, action, reward))
        state = (env.robot_position.copy(), env.robot_direction)
        if terminated:
            break
    return trajectory

# Q1.2: Random Policy
def random_policy(state):
    return np.random.choice([0, 1, 2])

# Q1.3: All-Forward Policy
def all_forward_policy(state):
    return 2

# Q1.4: Improved Custom Policy
def custom_policy(state):
    pos, direction = state
    next_pos = pos.copy()
    if direction == Directions.north:  # 0
        next_pos[1] -= 1
    elif direction == Directions.east:  # 1
        next_pos[0] += 1
    elif direction == Directions.south:  # 2
        next_pos[1] += 1
    elif direction == Directions.west:  # 3
        next_pos[0] -= 1
    if (next_pos[0] == 0 or next_pos[0] == 5 or
        next_pos[1] == 0 or next_pos[1] == 5):
        return 0  # Turn right
    return 2  # Move forward

# Initialize environment
env = DungeonMazeEnv(grid_size=6)

# Test each policy with multiple rollouts for better results
print("Random Policy:")
random_trajectory = rollout(env, random_policy)
print("Length:", len(random_trajectory))
print("Steps:", random_trajectory)

print("\nAll-Forward Policy:")
forward_trajectory = rollout(env, all_forward_policy)
print("Length:", len(forward_trajectory))
print("Steps:", forward_trajectory)

print("\nCustom Policy:")
custom_trajectory = rollout(env, custom_policy)
print("Length:", len(custom_trajectory))
print("Steps:", custom_trajectory)

import matplotlib.pyplot as plt

def plot_trajectory(trajectory, title):
    x = [state[0][0] for state, _, _ in trajectory]  # x coordinates
    y = [state[0][1] for state, _, _ in trajectory]  # y coordinates
    plt.plot(x, y, marker='o', label='Path')
    plt.scatter([4], [4], color='red', marker='x', label='Target [4, 4]')  # Add target
    plt.title(title)
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.xlim(0, 5)  # 6x6 grid: 0-5
    plt.ylim(0, 5)
    plt.grid(True)
    plt.legend()
    plt.show()

# Plot each trajectory
plot_trajectory(random_trajectory, "Random Policy Trajectory")
plot_trajectory(forward_trajectory, "All-Forward Policy Trajectory")
plot_trajectory(custom_trajectory, "Custom Policy Trajectory")

# Initialize environment
env = DungeonMazeEnv(grid_size=8)
env.reset()  # Fully initialize

# State space: (x, y, direction)
states = [(x, y, d) for x in range(8) for y in range(8) for d in range(4)]
actions = [0, 1, 2]
terminal_state = (-1, -1, -1)  # Define a terminal state for invalid moves

# Transition and reward dictionaries
T = {}
R = {}

# Assuming this is the relevant cell
import sys
sys.path.append('/content/SEMNTM016_DungeonMazeWorld')

from envs.simple_dungeonworld_env import DungeonMazeEnv
import numpy as np

# Initialize the environment with grid_size=6 (for Q1)
env = DungeonMazeEnv(grid_size=8)

# Reset the environment
observation = env.reset()

# Define actions (you might have defined this earlier; adjust as needed)
actions = [0, 1, 2]  # Example: 0=turn left, 1=turn right, 2=move forward

# Loop through actions with debugging
for a in actions:
    print(f"Action: {a}")
    print(f"Current position: {env.robot_position}")
    print(f"Current direction: {env.robot_direction}")
    next_obs, reward, terminated, _, _ = env.step(a)
    next_x, next_y = env.robot_position
    next_d = env.robot_direction
    print(f"Next position: {next_x, next_y}")
    print(f"Next direction: {next_d}")

# Build the model
for s in states:
    x, y, d = s
    env.robot_position = np.array([x, y])
    env.robot_direction = d
    T[s] = {}
    R[s] = {}
    for a in actions:
        try:
            next_obs, reward, terminated, _, _ = env.step(a)
            next_x, next_y = env.robot_position
            next_d = env.robot_direction
            next_s = (next_x, next_y, next_d)
            prob = 1.0 if not terminated or reward > 0 else 0.0
            T[s][a] = [(next_s, prob)]
            R[s][a] = reward if prob > 0 else -100
        except AssertionError:
            # Out-of-bounds move: transition to terminal state
            T[s][a] = [(terminal_state, 1.0)]
            R[s][a] = -100  # Penalty for hitting a wall
        env.robot_position = np.array([x, y])  # Reset
        env.robot_direction = d

# Add terminal state to T and R
T[terminal_state] = {a: [(terminal_state, 1.0)] for a in actions}
R[terminal_state] = {a: 0 for a in actions}  # No reward in terminal

# Test transitions
s = (1, 1, 2)  # [1, 1], south
print("State:", s)
for a in actions:
    print(f"Action {a}:")
    print("  Next state, prob:", T[s][a])
    print("  Reward:", R[s][a])

# Edge case test
s_edge = (7, 7, 2)  # [7, 7], south
print("\nEdge State:", s_edge)
for a in actions:
    print(f"Action {a}:")
    print("  Next state, prob:", T[s_edge][a])
    print("  Reward:", R[s_edge][a])

# Test transitions
s = (1, 1, 2)  # [1, 1], south
print("State:", s)
for a in actions:
    print(f"Action {a}:")
    print("  Next state, prob:", T[s][a])
    print("  Reward:", R[s][a])

# Edge case test
s_edge = (7, 7, 2)  # [7, 7], south
print("\nEdge State:", s_edge)
for a in actions:
    print(f"Action {a}:")
    print("  Next state, prob:", T[s_edge][a])
    print("  Reward:", R[s_edge][a])

# Q2.1: Initialize value table and random policy
# Value table: V(s) for each state, initialized to 0
V = {s: 0.0 for s in states}
V[terminal_state] = 0.0  # Terminal state has value 0

# Random policy: Uniform distribution over actions for each state
policy = {s: {a: 1.0 / len(actions) for a in actions} for s in states}
policy[terminal_state] = {a: 1.0 / len(actions) for a in actions}  # Doesn't matter for terminal state

# Discount factor
gamma = 1.0  # As specified in Q2

# Q2.1: Policy Evaluation
def policy_evaluation(V, policy, T, R, gamma, theta=1e-6, max_iterations=1000):
    """
    Evaluate the value function V for a given policy.
    Args:
        V: Value table {state: value}
        policy: Policy {state: {action: prob}}
        T: Transition model {state: {action: [(next_state, prob)]}}
        R: Reward model {state: {action: reward}}
        gamma: Discount factor
        theta: Convergence threshold
        max_iterations: Maximum number of iterations
    Returns:
        Updated value table V
    """
    for iteration in range(max_iterations):
        delta = 0.0
        # Update each state
        for s in states:  # Only update non-terminal states
            if s == terminal_state:
                continue
            v_old = V[s]
            # Compute new value using Bellman equation
            v_new = 0.0
            for a in actions:
                pi_a = policy[s][a]  # Probability of taking action a
                # Sum over possible next states (deterministic in this case)
                for next_s, prob in T[s][a]:
                    v_new += pi_a * prob * (R[s][a] + gamma * V[next_s])
            V[s] = v_new
            # Track the maximum change in value
            delta = max(delta, abs(v_old - V[s]))
        # Check for convergence
        if delta < theta:
            print(f"Policy evaluation converged after {iteration + 1} iterations")
            break
    else:
        print(f"Policy evaluation did not converge after {max_iterations} iterations")
    return V

# Run policy evaluation
V = policy_evaluation(V, policy, T, R, gamma)

# Test the value table
print("Value table for a few states after policy evaluation:")
for s in [(1, 1, 2), (7, 7, 2), (0, 0, 0)]:
    print(f"State {s}: V = {V[s]}")

# Q2.2: Policy Improvement
def policy_improvement(V, policy, T, R, gamma):
    """
    Improve the policy by choosing the action that maximizes the expected value.
    Args:
        V: Value table {state: value}
        policy: Policy {state: {action: prob}}
        T: Transition model {state: {action: [(next_state, prob)]}}
        R: Reward model {state: {action: reward}}
        gamma: Discount factor
    Returns:
        Updated policy, and a boolean indicating if the policy changed
    """
    policy_stable = True
    new_policy = {}

    for s in states:
        if s == terminal_state:
            new_policy[s] = policy[s]  # Terminal state policy doesn't matter
            continue

        # Find the action that maximizes the expected value
        best_action = None
        best_value = float('-inf')
        for a in actions:
            # Compute the expected value for this action
            value = 0.0
            for next_s, prob in T[s][a]:
                value += prob * (R[s][a] + gamma * V[next_s])
            if value > best_value:
                best_value = value
                best_action = a

        # Update the policy to be greedy: choose the best action with probability 1
        new_policy[s] = {a: 1.0 if a == best_action else 0.0 for a in actions}

        # Check if the policy changed
        old_action = max(policy[s], key=policy[s].get)  # Action with highest prob in old policy
        if old_action != best_action:
            policy_stable = False

    return new_policy, policy_stable

# Run policy improvement
policy, policy_stable = policy_improvement(V, policy, T, R, gamma)

# Test the new policy for a few states
print("Policy after improvement for a few states:")
for s in [(1, 1, 2), (7, 7, 2), (0, 0, 0)]:
    best_action = max(policy[s], key=policy[s].get)
    print(f"State {s}: Best action = {best_action}")

# Q2.3: Policy Iteration
def policy_iteration(V, policy, T, R, gamma, theta=1e-6, max_iterations=100):
    """
    Perform policy iteration to find the optimal policy and value table.
    Args:
        V: Initial value table {state: value}
        policy: Initial policy {state: {action: prob}}
        T: Transition model {state: {action: [(next_state, prob)]}}
        R: Reward model {state: {action: reward}}
        gamma: Discount factor
        theta: Convergence threshold for policy evaluation
        max_iterations: Maximum number of policy iteration steps
    Returns:
        Optimal value table V and optimal policy
    """
    for iteration in range(max_iterations):
        # Step 1: Policy Evaluation
        V = policy_evaluation(V, policy, T, R, gamma, theta)

        # Step 2: Policy Improvement
        policy, policy_stable = policy_improvement(V, policy, T, R, gamma)

        # Print progress
        print(f"Iteration {iteration + 1}: Policy stable = {policy_stable}")

        # Check for convergence
        if policy_stable:
            print("Policy iteration converged to optimal policy")
            break
    else:
        print(f"Policy iteration did not converge after {max_iterations} iterations")

    return V, policy

# Run policy iteration
V, policy = policy_iteration(V, policy, T, R, gamma)

# Test the final policy and value table
print("\nFinal value table and policy for a few states:")
for s in [(1, 1, 2), (7, 7, 2), (0, 0, 0)]:
    best_action = max(policy[s], key=policy[s].get)
    print(f"State {s}: V = {V[s]}, Best action = {best_action}")

# Q2.4: Initialize value table for value iteration
V_value_iter = {s: 0.0 for s in states}
V_value_iter[terminal_state] = 0.0  # Terminal state has value 0

# Q2.4: Value Iteration
def value_iteration(V, T, R, gamma, theta=1e-6, max_iterations=1000):
    """
    Perform value iteration to find the optimal value table.
    Args:
        V: Value table {state: value}
        T: Transition model {state: {action: [(next_state, prob)]}}
        R: Reward model {state: {action: reward}}
        gamma: Discount factor
        theta: Convergence threshold
        max_iterations: Maximum number of iterations
    Returns:
        Optimal value table V
    """
    for iteration in range(max_iterations):
        delta = 0.0
        # Update each state
        for s in states:
            if s == terminal_state:
                continue
            v_old = V[s]
            # Compute the maximum value over all actions
            max_value = float('-inf')
            for a in actions:
                value = 0.0
                for next_s, prob in T[s][a]:
                    value += prob * (R[s][a] + gamma * V[next_s])
                max_value = max(max_value, value)
            V[s] = max_value
            # Track the maximum change in value
            delta = max(delta, abs(v_old - V[s]))
        # Check for convergence
        if delta < theta:
            print(f"Value iteration converged after {iteration + 1} iterations")
            break
    else:
        print(f"Value iteration did not converge after {max_iterations} iterations")
    return V

# Run value iteration
V_value_iter = value_iteration(V_value_iter, T, R, gamma)

# Test the value table
print("\nValue table after value iteration for a few states:")
for s in [(1, 1, 2), (7, 7, 2), (0, 0, 0)]:
    print(f"State {s}: V = {V_value_iter[s]}")

# Q2.5: Extract Optimal Policy from Value Table
def extract_policy(V, T, R, gamma):
    """
    Extract the optimal policy from the optimal value table.
    Args:
        V: Optimal value table {state: value}
        T: Transition model {state: {action: [(next_state, prob)]}}
        R: Reward model {state: {action: reward}}
        gamma: Discount factor
    Returns:
        Optimal policy {state: {action: prob}}
    """
    policy = {}
    for s in states:
        if s == terminal_state:
            policy[s] = {a: 1.0 / len(actions) for a in actions}  # Doesn't matter for terminal state
            continue

        # Find the action that maximizes the expected value
        best_action = None
        best_value = float('-inf')
        for a in actions:
            value = 0.0
            for next_s, prob in T[s][a]:
                value += prob * (R[s][a] + gamma * V[next_s])
            if value > best_value:
                best_value = value
                best_action = a

        # Greedy policy: Choose the best action with probability 1
        policy[s] = {a: 1.0 if a == best_action else 0.0 for a in actions}

    return policy

# Extract the optimal policy from value iteration
policy_value_iter = extract_policy(V_value_iter, T, R, gamma)

# Compare with the policy from policy iteration
print("\nOptimal policy from value iteration for a few states:")
for s in [(1, 1, 2), (7, 7, 2), (0, 0, 0)]:
    best_action_value_iter = max(policy_value_iter[s], key=policy_value_iter[s].get)
    best_action_policy_iter = max(policy[s], key=policy[s].get)
    print(f"State {s}:")
    print(f"  Value iteration - Best action = {best_action_value_iter}")
    print(f"  Policy iteration - Best action = {best_action_policy_iter}")

import sys
sys.path.append('/content/SEMNTM016_DungeonMazeWorld')

from envs.simple_dungeonworld_env import DungeonMazeEnv
import numpy as np
import random

# Q3 Setup
# Initialize the environment with grid_size=10 (for Q3)
env = DungeonMazeEnv(grid_size=10)

# State space: (x, y, direction)
states = [(x, y, d) for x in range(10) for y in range(10) for d in range(4)]
actions = [0, 1, 2]  # 0=turn left, 1=turn right, 2=move forward

# Random policy: Uniform distribution over actions for each state
policy = {s: {a: 1.0 / len(actions) for a in actions} for s in states}

# Discount factor
gamma = 0.99  # As specified in Q3

# Q1.1 (assumed completed): Rollout function

def rollout(env, policy, max_steps=100):
    """
    Sample a complete trajectory in the environment using the given policy.
    Args:
        env: The environment (DungeonMazeEnv)
        policy: Policy {state: {action: prob}}
        max_steps: Maximum number of steps
    Returns:
        Trajectory as a list of tuples [(state, action, reward), ...]
    """
    trajectory = []
    # Call reset to ensure the environment is properly initialized
    env.reset()

    # Randomly select an initial position and direction
    x = random.randint(0, 9)  # Random x from 0 to 9 (grid_size=10)
    y = random.randint(0, 9)  # Random y from 0 to 9
    d = random.randint(0, 3)  # Random direction from 0 to 3
    env.robot_position = np.array([x, y])
    env.robot_direction = d
    state = (x, y, d)

    for _ in range(max_steps):
        # Convert state to tuple if it's not already (in case of numpy types)
        state = (int(state[0]), int(state[1]), int(state[2]))

        # Sample an action from the policy
        action_probs = policy[state]
        action = np.random.choice(actions, p=[action_probs[a] for a in actions])

        # Take the action
        try:
            next_obs, reward, terminated, _, _ = env.step(action)
            next_x, next_y = env.robot_position
            next_d = env.robot_direction
            next_state = (next_x, next_y, next_d)

            # Add to trajectory
            trajectory.append((state, action, reward))

            # Update state
            state = next_state

            # Check for termination
            if terminated:
                break
        except AssertionError:
            # Out-of-bounds move: Treat as termination
            trajectory.append((state, action, -100))  # Assume reward of -100 for hitting a wall
            break

    return trajectory


# Test the rollout function
env = DungeonMazeEnv(grid_size=10)  # Reinitialize to ensure a fresh start
trajectory = rollout(env, policy)
print("Sample trajectory (first 5 steps or until termination):")
for i, (state, action, reward) in enumerate(trajectory[:5]):
    print(f"Step {i}: State = {state}, Action = {action}, Reward = {reward}")
print(f"Trajectory length: {len(trajectory)}")

# Q3.1: Cumulative Reward Calculation Function
def calculate_cumulative_reward(trajectory, gamma):
    """
    Calculate the cumulative discounted reward for a trajectory.
    Args:
        trajectory: List of tuples [(state, action, reward), ...]
        gamma: Discount factor
    Returns:
        Cumulative reward (float)
    """
    cumulative_reward = 0.0
    for t, (_, _, reward) in enumerate(trajectory):
        cumulative_reward += (gamma ** t) * reward
    return cumulative_reward

# Test the cumulative reward function
# First, let's get the full trajectory (since the previous output only showed the first 5 steps)
env = DungeonMazeEnv(grid_size=10)  # Reinitialize to ensure a fresh start
trajectory = rollout(env, policy)
print("\nFull trajectory:")
for i, (state, action, reward) in enumerate(trajectory):
    print(f"Step {i}: State = {state}, Action = {action}, Reward = {reward}")

# Calculate and print the cumulative reward
cumulative_reward = calculate_cumulative_reward(trajectory, gamma)
print(f"\nCumulative reward for the trajectory: {cumulative_reward}")

# Q3.2: Monte-Carlo Sampling to Estimate Values for Each State
def monte_carlo_sampling(env, policy, num_episodes, gamma, max_steps=100):
    """
    Use Monte-Carlo sampling to estimate the value of each state.
    Args:
        env: The environment (DungeonMazeEnv)
        policy: Policy {state: {action: prob}}
        num_episodes: Number of episodes to sample
        gamma: Discount factor
        max_steps: Maximum number of steps per episode
    Returns:
        Value estimates {state: value}, and visit counts {state: count}
    """
    # Initialize value estimates and visit counts for each state
    V = {s: 0.0 for s in states}
    visits = {s: 0 for s in states}

    for episode in range(num_episodes):
        # Sample a trajectory
        trajectory = rollout(env, policy, max_steps)

        # Calculate the return (cumulative reward) for each state in the trajectory
        # First-visit Monte-Carlo: Only count the first visit to each state
        visited_states = set()
        for t, (state, action, reward) in enumerate(trajectory):
            # Convert state to tuple if it's not already (in case of numpy types)
            state = (int(state[0]), int(state[1]), int(state[2]))

            # Skip if we've already visited this state in this episode
            if state in visited_states:
                continue
            visited_states.add(state)

            # Calculate the return starting from this step
            sub_trajectory = trajectory[t:]
            G = calculate_cumulative_reward(sub_trajectory, gamma)

            # Update the value estimate using incremental mean
            visits[state] += 1
            V[state] += (G - V[state]) / visits[state]

    return V, visits

# Run Monte-Carlo sampling
num_episodes = 1000  # Number of episodes to sample (can adjust based on experimentation)
env = DungeonMazeEnv(grid_size=10)  # Reinitialize to ensure a fresh start
V_mc, visits_mc = monte_carlo_sampling(env, policy, num_episodes, gamma)

# Test the value estimates for a few states
print("\nMonte-Carlo value estimates for a few states:")
for s in [(1, 1, 2), (7, 7, 2), (0, 0, 0)]:
    print(f"State {s}: V = {V_mc[s]}, Visits = {visits_mc[s]}")

# Compute average value for each grid position (x, y)
V_grid = {}
visits_grid = {}
for x in range(10):
    for y in range(10):
        total_value = 0.0
        total_visits = 0
        for d in range(4):
            state = (x, y, d)
            total_value += V_mc[state] * visits_mc[state]
            total_visits += visits_mc[state]
        if total_visits > 0:
            V_grid[(x, y)] = total_value / total_visits
            visits_grid[(x, y)] = total_visits
        else:
            V_grid[(x, y)] = 0.0
            visits_grid[(x, y)] = 0

# Test the grid value estimates
print("\nMonte-Carlo value estimates for a few grid positions:")
for pos in [(1, 1), (7, 7), (0, 0)]:
    print(f"Grid {pos}: V = {V_grid[pos]}, Visits = {visits_grid[pos]}")

# Q3.3: Temporal Difference (TD) Learning
def td_learning(env, policy, num_episodes, gamma, alpha=0.1, theta=1e-6, max_steps=100):
    """
    Use TD(0) learning to estimate the value of each state.
    Args:
        env: The environment (DungeonMazeEnv)
        policy: Policy {state: {action: prob}}
        num_episodes: Number of episodes to sample
        gamma: Discount factor
        alpha: Learning rate
        theta: Convergence threshold
        max_steps: Maximum number of steps per episode
    Returns:
        Value estimates {state: value}
    """
    # Initialize value table
    V = {s: 0.0 for s in states}
    terminal_state = (-1, -1, -1)  # Define terminal state as in Q2
    V[terminal_state] = 0.0  # Terminal state value is 0

    # Track convergence
    episode = 0
    while episode < num_episodes:
        # Sample a trajectory
        trajectory = rollout(env, policy, max_steps)

        # Track the maximum change in values for this episode
        delta = 0.0

        # Perform TD updates for each step in the trajectory
        for t in range(len(trajectory)):
            state, action, reward = trajectory[t]
            state = (int(state[0]), int(state[1]), int(state[2]))

            # Get the next state (if not the last step)
            if t < len(trajectory) - 1:
                next_state = trajectory[t + 1][0]
                next_state = (int(next_state[0]), int(next_state[1]), int(next_state[2]))
            else:
                # If this is the last step, assume termination (next state is terminal)
                next_state = terminal_state

            # TD update
            td_target = reward + gamma * V[next_state]
            td_error = td_target - V[state]
            V[state] += alpha * td_error

            # Track the maximum change
            delta = max(delta, abs(alpha * td_error))

        episode += 1

        # Check for convergence
        if delta < theta:
            print(f"TD learning converged after {episode} episodes")
            break

    if episode == num_episodes:
        print(f"TD learning did not converge after {num_episodes} episodes")

    return V

# Run TD learning
num_episodes = 1000  # Same number of episodes as Monte-Carlo
alpha = 0.1  # Learning rate (can adjust in Q3.4)
env = DungeonMazeEnv(grid_size=10)  # Reinitialize to ensure a fresh start
V_td = td_learning(env, policy, num_episodes, gamma, alpha)

# Test the TD value estimates for a few states
print("\nTD value estimates for a few states:")
for s in [(1, 1, 2), (7, 7, 2), (0, 0, 0)]:
    print(f"State {s}: V = {V_td[s]}")

import matplotlib.pyplot as plt

# Create a 10x10 grid of values
grid_values = np.zeros((10, 10))
for x in range(10):
    for y in range(10):
        grid_values[x, y] = V_grid[(x, y)]

# Plot the heatmap
plt.imshow(grid_values, cmap='coolwarm', interpolation='nearest')
plt.colorbar(label='Value')
plt.title('Monte-Carlo Value Estimates for Each Grid Position')
plt.xlabel('Y')
plt.ylabel('X')
plt.show()
