# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2qiWNf6q8KTtgX0keNE52KB6cgPjlsm
"""

# Import necessary libraries
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from google.colab import files  # For uploading files in Colab
import zipfile
import os

# Step 1: Upload datasets to Colab
print("Upload dungeon_images_colour80.zip and dungeon_sensorstats.partC.csv")
uploaded = files.upload()

sensor_path = "/content/dungeon_sensorstats_partC.csv"
zip_path = "/content/dungeon_images_colour80.zip"
extracted_dir = "/content/sample_data/images_folder"

# Step 3: Extract the zip file (images)
if not os.path.exists(extracted_dir):
    os.makedirs(extracted_dir)  # Create folder if it doesn’t exist
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extracted_dir)
image_dir = extracted_dir  # Path to extracted images

# Check if sensor file exists, upload if missing
if not os.path.exists(sensor_path):
    print(f"File not found at {sensor_path}. Please upload dungeon_sensorstats.partC.csv")
    uploaded = files.upload()
    for filename in uploaded.keys():
        if "dungeon_sensorstats.partC.csv" in filename:
            os.rename(filename, sensor_path)
            print(f"Moved {filename} to {sensor_path}")
        else:
            print("Uploaded file doesn’t match expected name.")
            raise FileNotFoundError("Incorrect file uploaded")

# Step 4: Load and preprocess sensor data
sensor_data = pd.read_csv(sensor_path)
sensor_data["bribe"] = sensor_data["bribe"].fillna(0)  # Handle missing values in 'bribe'

# Handle missing 'race' values
print("Number of missing 'race' values:", sensor_data["race"].isna().sum())
most_common_race = sensor_data["race"].mode()[0]
print(f"Most common race: {most_common_race}")
sensor_data["race"] = sensor_data["race"].fillna(most_common_race)

# Handle missing values in numeric columns
numeric_columns = ["stench", "sound", "heat", "intelligence", "height", "weight", "strength", "bribe"]
for col in numeric_columns:
    print(f"Number of missing values in {col}:", sensor_data[col].isna().sum())
    sensor_data[col] = sensor_data[col].fillna(sensor_data[col].mean())  # Impute with mean

sensor_features = sensor_data[numeric_columns]
scaler = MinMaxScaler()
sensor_X = scaler.fit_transform(sensor_features)
flight_Y = sensor_data["flight"].values

# Step 5: Load and preprocess image data
# Update image_dir to point to the subfolder
image_dir = os.path.join(extracted_dir, "dungeon_images_colour80")  # /content/sample_data/images_folder/dungeon_images_colour80

# Inspect the image folder
image_filenames = os.listdir(image_dir)
print("Number of items found:", len(image_filenames))
print("All items:", image_filenames)  # Show all to confirm subfolders

# Identify race subfolders (ignore non-race items like '.DS_Store', 'info.text')
race_subfolders = [f for f in image_filenames if f in ['human', 'wingedrat', 'halfling', 'lizard', 'orc']]
print("Race subfolders:", race_subfolders)

# Count total images across subfolders and inspect filenames
total_images = 0
image_files_by_race = {}  # Store sorted list of image filenames for each race
for race in race_subfolders:
    race_dir = os.path.join(image_dir, race)
    race_images = [f for f in os.listdir(race_dir) if f.lower().endswith('.png')]
    race_images.sort()  # Sort filenames to ensure consistent order
    image_files_by_race[race] = race_images
    print(f"Number of images in {race} folder: {len(race_images)}")
    print(f"Sample filenames in {race} folder:", race_images[:5])
    total_images += len(race_images)
print("Total images across all subfolders:", total_images)

# Inspect filenames in one subfolder to determine naming convention
sample_race = 'human'  # Choose one race to inspect
sample_race_dir = os.path.join(image_dir, sample_race)
sample_images = [f for f in os.listdir(sample_race_dir) if f.endswith('.png')]
print(f"Sample filenames in {sample_race} folder:", sample_images[:5])

# Load images, matching to sensor_data rows
image_X = []
image_counter = {race: 0 for race in race_subfolders}  # Track how many images we've used per race

for i in range(len(sensor_data)):  # 10,000 samples
    race = sensor_data["race"].iloc[i]  # e.g., "human", "wingedrat"
    if race not in race_subfolders:
        print(f"Race {race} not found in subfolders. Using placeholder for index {i}.")
        image_X.append(np.zeros((80, 80, 3)))
        continue

    # Get the list of images for this race
    race_images = image_files_by_race[race]
    img_index = image_counter[race]

    # Check if we have more images to load for this race
    if img_index < len(race_images):
        img_filename = race_images[img_index]
        img_path = os.path.join(image_dir, race, img_filename)
        img = tf.keras.preprocessing.image.load_img(img_path, target_size=(80, 80))
        img_array = tf.keras.preprocessing.image.img_to_array(img) / 255.0  # Normalize to [0, 1]
        image_X.append(img_array)
    else:
        print(f"No more images available for race {race} at index {i}. Using placeholder.")
        image_X.append(np.zeros((80, 80, 3)))  # Placeholder: black image

    # Increment counter
    image_counter[race] += 1

image_X = np.array(image_X)  # Convert to numpy array

# Verify shapes
print("Image data shape:", image_X.shape)  # Should be (10000, 80, 80, 3)
print("Sensor data shape:", sensor_X.shape)  # Should be (10000, 8)
print("Labels shape:", flight_Y.shape)      # Should be (10000,)

# Visualize a sample image to confirm
plt.imshow(image_X[0])
plt.title(f"Sample Image (Flight: {flight_Y[0]})")
plt.show()

# Step 6: Split data into train and test sets
X_img_train, X_img_test, X_sensor_train, X_sensor_test, y_train, y_test = train_test_split(
    image_X, sensor_X, flight_Y, test_size=0.2, stratify=flight_Y, random_state=42
)

# Verify split shapes
print("Training image data shape:", X_img_train.shape)
print("Test image data shape:", X_img_test.shape)
print("Training sensor data shape:", X_sensor_train.shape)
print("Test sensor data shape:", X_sensor_test.shape)
print("Training labels shape:", y_train.shape)
print("Test labels shape:", y_test.shape)

# Debug: Check for nan or inf in the data
print("Checking for nan/inf in image_X:")
print("image_X has nan:", np.any(np.isnan(image_X)))
print("image_X has inf:", np.any(np.isinf(image_X)))
print("image_X min/max:", image_X.min(), image_X.max())

print("\nChecking for nan/inf in sensor_X:")
print("sensor_X has nan:", np.any(np.isnan(sensor_X)))
print("sensor_X has inf:", np.any(np.isinf(sensor_X)))
print("sensor_X min/max:", sensor_X.min(), sensor_X.max())

print("\nChecking for nan in flight_Y:")
print("flight_Y has nan:", np.any(np.isnan(flight_Y)))
print("flight_Y unique values:", np.unique(flight_Y))

# Debug: Check class distribution in flight_Y
print("Class distribution in flight_Y (overall):", np.bincount(flight_Y))
print("Class distribution in y_train:", np.bincount(y_train))
print("Class distribution in y_test:", np.bincount(y_test))

# Debug: Check correlation between race and flight
race_flight_crosstab = pd.crosstab(sensor_data["race"], sensor_data["flight"])
print("Crosstab of race vs flight:")
print(race_flight_crosstab)

# Step 7: Build the multi-modal CNN model
# Image input branch
image_input = tf.keras.Input(shape=(80, 80, 3), name="image_input")
x = tf.keras.layers.Conv2D(32, (3, 3), activation="relu")(image_input)
x = tf.keras.layers.MaxPooling2D((2, 2))(x)
x = tf.keras.layers.Conv2D(64, (3, 3), activation="relu")(x)
x = tf.keras.layers.MaxPooling2D((2, 2))(x)
x = tf.keras.layers.Flatten()(x)
image_dense = tf.keras.layers.Dense(128, activation="relu")(x)

# Sensor input branch
sensor_input = tf.keras.Input(shape=(8,), name="sensor_input")  # 8 features
sensor_dense = tf.keras.layers.Dense(64, activation="relu")(sensor_input)

# Fuse the two branches
fused = tf.keras.layers.Concatenate()([image_dense, sensor_dense])
fused_dense = tf.keras.layers.Dense(64, activation="relu")(fused)
output = tf.keras.layers.Dense(1, activation="sigmoid")(fused_dense)  # Binary output

# Create model
model = tf.keras.Model(inputs=[image_input, sensor_input], outputs=output)

# Compile model
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

# Model summary
model.summary()

# Train the model
history = model.fit(
    [X_img_train, X_sensor_train], y_train,
    validation_data=([X_img_test, X_sensor_test], y_test),
    epochs=20,
    batch_size=32,
    verbose=1
)

# Step 8: Evaluate the model and plot training history
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix
import seaborn as sns

# Evaluate on test set
test_loss, test_accuracy = model.evaluate([X_img_test, X_sensor_test], y_test, verbose=0)
print(f"Test Loss: {test_loss:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

# Get predictions
y_pred = model.predict([X_img_test, X_sensor_test])
y_pred_binary = (y_pred > 0.5).astype(int).flatten()

# Calculate precision, recall, and F1-score
precision = precision_score(y_test, y_pred_binary)
recall = recall_score(y_test, y_pred_binary)
f1 = f1_score(y_test, y_pred_binary)
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")

# Confusion matrix
cm = confusion_matrix(y_test, y_pred_binary)
plt.figure(figsize=(6, 4))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=["No Flight", "Flight"], yticklabels=["No Flight", "Flight"])
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.show()

# Plot training history
plt.figure(figsize=(12, 4))

# Plot accuracy
plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()

# Plot loss
plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()

plt.tight_layout()
plt.show()

