# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZMCVXNTp84gZFAnN_4OLytK_D7qQGCs
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture

# --- Question 1: Supervised Classification ---
# Load dataset
sprites_data = np.load("sprites_greyscale10.npz")
train_X, train_Y = sprites_data["train_X"], sprites_data["train_Y"]
test_X, test_Y = sprites_data["test_X"], sprites_data["test_Y"]

original_train_size = train_X.shape[0]
original_test_size = test_X.shape[0]
print(f"Original training size: {original_train_size}")
print(f"Original test size: {original_test_size}")

# Find unique classes
unique_classes = np.unique(train_Y)
if len(unique_classes) < 2:
    raise ValueError("Dataset does not contain enough classes!")

# Select first two unique classes
class_1, class_2 = unique_classes[:2]
print(f"Using classes: {class_1}, {class_2}")

# Filter dataset to only these two classes
mask_train = (train_Y == class_1) | (train_Y == class_2)
mask_test = (test_Y == class_1) | (test_Y == class_2)

X_train, y_train = train_X[mask_train], train_Y[mask_train]
X_test, y_test = test_X[mask_test], test_Y[mask_test]

# Check if filtering worked
print("Filtered training size:", X_train.shape)
print("Filtered test size:", X_test.shape)

train_percent = (X_train.shape[0] / original_train_size) * 100
test_percent = (X_test.shape[0] / original_test_size) * 100
print(f"Percentage of original training data retained: {train_percent:.2f}%")
print(f"Percentage of original test data retained: {test_percent:.2f}%")

# Reshape images for classifiers
if X_train.shape[0] > 0 and X_test.shape[0] > 0:
    X_train = X_train.reshape(X_train.shape[0], -1)
    X_test = X_test.reshape(X_test.shape[0], -1)
else:
    raise ValueError("Filtering resulted in empty datasets. Check class selection!")

# Train classifiers
models = {
    "Decision Tree": DecisionTreeClassifier(),
    "KNN": KNeighborsClassifier(n_neighbors=5),
    "Logistic Regression": LogisticRegression()
}

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test, y_pred)
    print(f"{name} Accuracy: {acc:.4f}")

# --- Question 2: Supervised Regression ---
# Load dataset
dungeon_train = pd.read_csv("dungeon_sensorstats_train.csv")
dungeon_test = pd.read_csv("dungeon_sensorstats_test.csv")

# Select human class and relevant features
features = ["intelligence", "stench", "sound", "heat"]
train_humans = dungeon_train[dungeon_train['race'] == 'human'][features + ['bribe']]
test_humans = dungeon_test[dungeon_test['race'] == 'human'][features + ['bribe']]

train_samples = train_humans.shape[0]
test_samples = test_humans.shape[0]
print(f"Number of training samples (humans): {train_samples}")
print(f"Number of test samples (humans): {test_samples}")

X_train, y_train = train_humans[features], train_humans['bribe']
X_test, y_test = test_humans[features], test_humans['bribe']

# Train Linear Regression Model
reg_model = LinearRegression()
reg_model.fit(X_train, y_train)
y_pred = reg_model.predict(X_test)
print("MSE (Multiple Features):", mean_squared_error(y_test, y_pred))

# Train Single Feature Regression Model
single_feature = "intelligence"
X_train_single = X_train[[single_feature]]
X_test_single = X_test[[single_feature]]

single_reg_model = LinearRegression()
single_reg_model.fit(X_train_single, y_train)
y_pred_single = single_reg_model.predict(X_test_single)
print(f"MSE (Single Feature - {single_feature}):", mean_squared_error(y_test, y_pred_single))

# Visualization
plt.scatter(X_test_single, y_test, label="True Values")
plt.plot(X_test_single, y_pred_single, color='red', label="Regression Line")
plt.xlabel(single_feature)
plt.ylabel("Bribe Amount")
plt.legend()
plt.show()

# --- Question 3: Unsupervised Clustering ---
# Load dataset
dungeon_data = pd.read_csv("dungeon_sensorstats.csv")

total_samples = dungeon_data.shape[0]
print(f"Total number of samples in dungeon_sensorstats.csv: {total_samples}")

# Select two features
features = ["height", "weight"]
X_cluster = dungeon_data[features]

# KMeans Clustering
kmeans = KMeans(n_clusters=3, random_state=42)
kmeans_labels = kmeans.fit_predict(X_cluster)

dungeon_data["KMeans_Cluster"] = kmeans_labels
sns.scatterplot(x="height", y="weight", hue="KMeans_Cluster", data=dungeon_data, palette="deep")
plt.title("K-Means Clustering")
plt.show()

# Gaussian Mixture Model (GMM)
gmm = GaussianMixture(n_components=3, random_state=42)
gmm_labels = gmm.fit_predict(X_cluster)

dungeon_data["GMM_Cluster"] = gmm_labels
sns.scatterplot(x="height", y="weight", hue="GMM_Cluster", data=dungeon_data, palette="deep")
plt.title("Gaussian Mixture Model Clustering")
plt.show()
